# python3 /home/david/Desktop/projects/thesis/combined_downstream_upstream/code/ptb-turned_off_channels-no_added_noise-impute_only_missing_multitask-with-varying-reconstruction.py  --num_channels_to_turn_off 0
# python3 /home/david/Desktop/projects/thesis/combined_downstream_upstream/code/ptb-turned_off_channels-no_added_noise-impute_only_missing_multitask-with-varying-reconstruction.py  --num_channels_to_turn_off 1
python3 /home/david/Desktop/projects/thesis/combined_downstream_upstream/code/ptb-turned_off_channels-no_added_noise-impute_only_missing_multitask-with-varying-reconstruction.py  --num_channels_to_turn_off 2
python3 /home/david/Desktop/projects/thesis/combined_downstream_upstream/code/ptb-turned_off_channels-no_added_noise-impute_only_missing_multitask-with-varying-reconstruction.py  --num_channels_to_turn_off 3
python3 /home/david/Desktop/projects/thesis/combined_downstream_upstream/code/ptb-turned_off_channels-no_added_noise-impute_only_missing_multitask-with-varying-reconstruction.py  --num_channels_to_turn_off 4
python3 /home/david/Desktop/projects/thesis/combined_downstream_upstream/code/ptb-turned_off_channels-no_added_noise-impute_only_missing_multitask-with-varying-reconstruction.py  --num_channels_to_turn_off 5
python3 /home/david/Desktop/projects/thesis/combined_downstream_upstream/code/ptb-turned_off_channels-no_added_noise-impute_only_missing_multitask-with-varying-reconstruction.py  --num_channels_to_turn_off 6
python3 /home/david/Desktop/projects/thesis/combined_downstream_upstream/code/ptb-turned_off_channels-no_added_noise-impute_only_missing_multitask-with-varying-reconstruction.py  --num_channels_to_turn_off 7
python3 /home/david/Desktop/projects/thesis/combined_downstream_upstream/code/ptb-turned_off_channels-no_added_noise-impute_only_missing_multitask-with-varying-reconstruction.py  --num_channels_to_turn_off 8
python3 /home/david/Desktop/projects/thesis/combined_downstream_upstream/code/ptb-turned_off_channels-no_added_noise-impute_only_missing_multitask-with-varying-reconstruction.py  --num_channels_to_turn_off 9
python3 /home/david/Desktop/projects/thesis/combined_downstream_upstream/code/ptb-turned_off_channels-no_added_noise-impute_only_missing_multitask-with-varying-reconstruction.py  --num_channels_to_turn_off 10
python3 /home/david/Desktop/projects/thesis/combined_downstream_upstream/code/ptb-turned_off_channels-no_added_noise-impute_only_missing_multitask-with-varying-reconstruction.py  --num_channels_to_turn_off 11